:cow2: #29 #31 Auth0でのログイン・ユーザー登録機能実装（LINE・Google）
satou-haruka-37/hokkaido_travel pull request #115
Opened 2023-12-14 23:53 UTC by satou-haruka-37

## 概要
- ユーザー登録、ログイン機能（Auth0）
- Googleログイン設定
- LINEログイン設定

## 確認方法
- ヘッダーのログインボタンから、GoogleまたはLINEでログインが成功すると、トップページにリダイレクトされヘッダーのloginがlogoutに変わることを確認します。
- 初回ログインの際にはデータベースにユーザーが追加されることを確認します。
- ログインしないと利用できないページはまだ作っていないので、上記の確認のみとなります🙇

## 環境構築方法

1. `$ git clone -b feature/login https://github.com/satou-haruka-37/hokkaido_travel.git`
2. `$ touch .env`
3. `$ cd docker`
4. `$ cp database.yml.docker ../config/database.yml`
5. `$ docker compose up`

2023-12-16 16:00 UTC, Gitnana00 requested changes

2023-12-16 16:12 UTC, satou-haruka-37 commented on app/models/user.rb
> +    user.save if user.changed? # 変更がある場合のみ保存
`user = find_or_initialize_by(uid: uid)`
ここで、usersテーブルから、送られてきた`uid = auth[:uid]`と一致するuidのユーザーがいるか確認して、無ければuserを作っています！

2023-12-16 17:02 UTC, satou-haruka-37 commented on config/initializers/auth0.rb
> +end
レビューありがとうございます🙇
該当の部分を修正しました。
お時間のある時に確認をお願いします。

2023-12-17 03:52 UTC, Gitnana00 commented on app/models/user.rb
> +    user.save if user.changed? # 変更がある場合のみ保存
なるほど！！ありがとうございます！！

2023-12-17 07:10 UTC, merged